/* ColorVerse — AI-generated coloring page catalog (62 pages). Images in /catalog. */
const CATALOG = [
  {id:"lion", title:"Friendly Lion", cat:"animals", level:"beginner"},
  {id:"elephant", title:"Elephant & Balloons", cat:"animals", level:"beginner"},
  {id:"owl", title:"Wise Owl", cat:"animals", level:"intermediate"},
  {id:"turtle", title:"Sea Turtle", cat:"animals", level:"beginner"},
  {id:"panda", title:"Baby Panda", cat:"animals", level:"beginner"},
  {id:"rabbit", title:"Spring Rabbit", cat:"animals", level:"beginner"},
  {id:"fox-forest", title:"Forest Fox", cat:"animals", level:"intermediate"},
  {id:"dolphin", title:"Leaping Dolphin", cat:"animals", level:"beginner"},
  {id:"butterfly-garden", title:"Garden Butterfly", cat:"animals", level:"intermediate"},
  {id:"horse", title:"Galloping Horse", cat:"animals", level:"advanced"},
  {id:"cat-yarn", title:"Kitten & Yarn", cat:"animals", level:"beginner"},
  {id:"penguin", title:"Happy Penguin", cat:"animals", level:"beginner"},
  {id:"rose", title:"Single Rose", cat:"nature", level:"beginner"},
  {id:"sunflower", title:"Sunflower", cat:"nature", level:"beginner"},
  {id:"tree-of-life", title:"Tree of Life", cat:"nature", level:"advanced"},
  {id:"mushroom-house", title:"Mushroom House", cat:"nature", level:"intermediate"},
  {id:"cactus", title:"Potted Cactus", cat:"nature", level:"beginner"},
  {id:"flower-bouquet", title:"Flower Bouquet", cat:"nature", level:"intermediate"},
  {id:"mountain-scene", title:"Mountain Lake", cat:"nature", level:"intermediate"},
  {id:"autumn-leaf", title:"Autumn Leaves", cat:"nature", level:"beginner"},
  {id:"unicorn", title:"Magic Unicorn", cat:"fantasy", level:"beginner"},
  {id:"dragon", title:"Baby Dragon", cat:"fantasy", level:"intermediate"},
  {id:"castle", title:"Fairytale Castle", cat:"fantasy", level:"advanced"},
  {id:"mermaid", title:"Mermaid", cat:"fantasy", level:"intermediate"},
  {id:"fairy", title:"Flower Fairy", cat:"fantasy", level:"beginner"},
  {id:"wizard", title:"Wizard", cat:"fantasy", level:"intermediate"},
  {id:"phoenix", title:"Phoenix", cat:"fantasy", level:"advanced"},
  {id:"mandala-simple", title:"Simple Mandala", cat:"mandala", level:"beginner"},
  {id:"mandala-floral", title:"Floral Mandala", cat:"mandala", level:"intermediate"},
  {id:"mandala-ornate", title:"Ornate Mandala", cat:"mandala", level:"advanced"},
  {id:"mandala-star", title:"Star Mandala", cat:"mandala", level:"intermediate"},
  {id:"mandala-lotus", title:"Lotus Mandala", cat:"mandala", level:"advanced"},
  {id:"pattern-geometric", title:"Geometric Pattern", cat:"patterns", level:"intermediate"},
  {id:"pattern-paisley", title:"Paisley Pattern", cat:"patterns", level:"advanced"},
  {id:"pattern-floral", title:"Floral Pattern", cat:"patterns", level:"intermediate"},
  {id:"pattern-waves", title:"Wave Pattern", cat:"patterns", level:"beginner"},
  {id:"car", title:"Race Car", cat:"vehicles", level:"beginner"},
  {id:"rocket", title:"Space Rocket", cat:"vehicles", level:"beginner"},
  {id:"train", title:"Steam Train", cat:"vehicles", level:"intermediate"},
  {id:"airplane", title:"Airplane", cat:"vehicles", level:"beginner"},
  {id:"sailboat", title:"Sailboat", cat:"vehicles", level:"beginner"},
  {id:"tractor", title:"Farm Tractor", cat:"vehicles", level:"beginner"},
  {id:"fire-truck", title:"Fire Truck", cat:"vehicles", level:"intermediate"},
  {id:"octopus", title:"Octopus", cat:"ocean", level:"beginner"},
  {id:"seahorse", title:"Seahorse", cat:"ocean", level:"intermediate"},
  {id:"whale", title:"Friendly Whale", cat:"ocean", level:"beginner"},
  {id:"crab", title:"Beach Crab", cat:"ocean", level:"beginner"},
  {id:"coral-reef", title:"Coral Reef", cat:"ocean", level:"advanced"},
  {id:"astronaut", title:"Astronaut", cat:"space", level:"intermediate"},
  {id:"planet-rings", title:"Ringed Planet", cat:"space", level:"beginner"},
  {id:"alien", title:"Friendly Alien", cat:"space", level:"beginner"},
  {id:"solar-system", title:"Solar System", cat:"space", level:"advanced"},
  {id:"cupcake", title:"Cupcake", cat:"food", level:"beginner"},
  {id:"ice-cream", title:"Ice Cream", cat:"food", level:"beginner"},
  {id:"fruit-bowl", title:"Fruit Bowl", cat:"food", level:"intermediate"},
  {id:"birthday-cake", title:"Birthday Cake", cat:"food", level:"intermediate"},
  {id:"trex", title:"T-Rex", cat:"dinosaurs", level:"beginner"},
  {id:"stegosaurus", title:"Stegosaurus", cat:"dinosaurs", level:"intermediate"},
  {id:"brachiosaurus", title:"Brachiosaurus", cat:"dinosaurs", level:"beginner"},
  {id:"christmas-tree", title:"Christmas Tree", cat:"holidays", level:"beginner"},
  {id:"pumpkin", title:"Halloween Pumpkin", cat:"holidays", level:"beginner"},
  {id:"easter-egg", title:"Easter Eggs", cat:"holidays", level:"intermediate"},
];
const CAT_META = [
  {id:"animals", label:"Animals", emoji:"\ud83d\udc3e"},
  {id:"fantasy", label:"Fantasy", emoji:"\ud83e\udd84"},
  {id:"dinosaurs", label:"Dinosaurs", emoji:"\ud83e\udd95"},
  {id:"ocean", label:"Ocean", emoji:"\ud83c\udf0a"},
  {id:"space", label:"Space", emoji:"\ud83d\ude80"},
  {id:"vehicles", label:"Vehicles", emoji:"\ud83d\ude97"},
  {id:"nature", label:"Nature", emoji:"\ud83c\udf3f"},
  {id:"food", label:"Food", emoji:"\ud83e\uddc1"},
  {id:"mandala", label:"Mandala", emoji:"\ud83c\udf00"},
  {id:"patterns", label:"Patterns", emoji:"\ud83d\udd37"},
  {id:"holidays", label:"Holidays", emoji:"\ud83c\udf89"},
];
const catImg = (id) => 'catalog/' + id + '.png';
